theme: minima
title: MECooking
author: Matthew McKinney
description: This will be a website where Emma and I can document our favorite recipes together.
url: https://mm100301.github.io
baseurl: /MECooking

collections_dir: "_recipes"
collections:
  beef:
    label: beef
    output: true
    permalink: MECooking/_recipes/_beef/:title
  bread:
    label: bread
    output: true
    permalink: MECooking/_recipes/_bread/:title
  chicken:
    label: chicken
    output: true
    permalink: MECooking/_recipes/_chicken/:title
  dessert:
    label: dessert
    output: true
    permalink: MECooking/_recipes/_dessert/:title
  other:
    label: other
    output: true
    permalink: MECooking/_recipes/_other/:title
  party dishes:
    label: party dishes
    output: true
    permalink: MECooking/_recipes/_party_dishes/:title
  pasta:
    label: pasta
    output: true
    permalink: MECooking/_recipes/_pasta/:title
  seafood:
    label: seafood
    output: true
    permalink: MECooking/_recipes/_seafood/:title
  sides:
    label: sides
    output: true
    permalink: MECooking/_recipes/_sides/:title
  test:
    label: test
    output: true
    permalink: MECooking/_recipes/_test/:title


include:
  - _beef
  - _bread
  - _chicken
  - _data
  - _dessert
  - _other
  - _party_dishes
  - _pasta
  - _pages
  - _recipes
  - _seafood
  - _sides
  - _test


enable_darkmode: true